lidar_topic: ["/ouster/points",
              "/nt_topic/sensor/lidar3d_32_right_front_high", 
              "/nt_topic/sensor/lidar3d_32_left_front_high", 
              "/nt_topic/sensor/lidar3d_32_top_front", 
              "/nt_topic/sensor/lidar3d_m1_front",
              "/nt_topic/sensor/lidar3d_m1_left_front_low"]
lidar_num: 6
icp_score_the: 0.12
# extrinsic_T: [0.0, 0.0, 0.0,
#               0.0, 0.0, 0.0,
#               0.0, 0.0, 0.0,
#               0.0, 0.0, 0.0,
#               0.0, 0.0, 0.0]
# extrinsic_R: [.0
# ,
#               0.5374,0,0,0.8434,
#               0,1,0,0,
#               1,0,0,0,
#               0.5374,0,0,0.8434]

# extrinsic_T: [-3.0, 6.0, 0.0,
#               -3.0, 3.0, 0.0,
#               -1.0, 5.0, 3.0,
#               -3.0, 3.0, 0.0,
#               -3.0, 3.0, 0.0,
#               -3.0, 3.0, 0.0]
# extrinsic_R: [0.8434,0,0,0.5374,
#               0.8434,0,0,-0.5374,
#               0,0,1,0,
#               0,0,0,1,
#               0.8434,0,0,-0.5374,
#               1,0,0,0]
extrinsic_T: [-3.0, -3.0, 0.0,
              -3.0, -6.0, 0.0,
              -3.0, -3.0, 0.0,
              -1.0, -4.0, -2.0,
              -3.0, -3.0, 0.0,
              -3.0, -3.0, 0.0]
extrinsic_R: [0,1,0,0,
              0,0.8660,-0.5000,0,
              0,0.8660,0.5000,0,
              0,0,0,1,
              0,0,1,0,
              0,0.8660,0.5000,0]